### PR TITLE
separating the check for projectId and credentials fixes #9

### LINKED ISSUE #9: projectId does not seem to work in the deploy config
Howdy folks 👋 

I've just tried to specify the projectId using the ENV in deploy.js: 

```
    ENV['gcloud-storage'] = {
      projectId: 'super-awesome-project',
      bucket: 'best-bucket'
    };
```
but this doesn't work. I needed to do it on command line like this: `GCLOUD_PROJECT=super-awesome-project ember deploy production`

### PR DESCRIPTION
**Pull request by mansona**
I've tested this and it's working now as expected 👍

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -44,14 +44,16 @@ module.exports = {
...
+          metadata: metadata,
+          gcloud: {},
         };
 
-        if (projectId && credentials) {
-          config['gcloud'] = {
-            credentials: credentials,
-            projectId: projectId
-          };
+        if ( projectId ) {
```
Comment (knownasilya) [inline index.js]: Could you remove the spaces inside the`(`? So have `if (projectId) {` instead. Thanks

File: index.js [hunk 2]
```diff
@@ -44,14 +44,16 @@ module.exports = {
...
+          config.gcloud.projectId = projectId;
+        }
+
+        if ( credentials ) {
```
Comment (knownasilya) [inline index.js]: Same as above

**Review by knownasilya — CHANGES_REQUESTED** [review]
